language: node_js
node_js:
- 9
install:
  - pip install --user awscli
script: exit 0
deploy:
  provider: s3
  access_key_id: AKIAJVF46MNZ7SUUD5IQ
  secret_access_key:
    secure: prvic0NuElP01dp/s5NqPqLv8Cnf4mUJRdVPBS0F1eP4EdQ8Lu6zTISKA/o6fH0h0/SwMZScGBn3s06Leg8uUDRT0eNvwc0bRkIbmY5GdKM1aT0Vom1Tme2NuWa2N1FFD16bXBxvIfmTnM5eIGKagXTvK/yymns0DYjpFAwRdVGfw7eW+Nyyoki85rmvw1NVUmB12aiwaA21xqFsh9Ibp5a8nnBgTNvUGxi7VqZ734i2luILsdZps8pnMOS3uVZhdsITfiianobyrD4VUNHbO4G1Z9PrhEF1xa6FXBZgjAUFoGzOoVtSkyGS9FczIOx142IW+Q6Je0KUcajCETuZfU37H2aNlevseW5S98CY7+CYql5Rc/2z5jSpTo+MQnUC2qZr+OkMMLQ0tDVhGwrn8W1/pG46ByC418tJZiJjz7NBhHe93IbAle7nP9eCr7DAk5N7a1w4wTzm3J7h5UzYZLb5nvK8QCL+Hakpfd4ivjeOHdF9OZ1lFfC0V2JhnDeb2A9deAkeh3nfa10FT+2bdWmyzh6/f+RiF1+MKudzcBd9MeKpXEjbmiD6U8ysnsKZ844UIcuevIPtdqV6465Sj1qGn0t4hWAIZz7TI3CMu7QYoWx347QcbhWYybPn/f9HcXmW/OtAIxa1dkK5W8yf7Wk1R+P6myO9zZWDuhwM24k=
  bucket: www.unas.io
  region: us-east-2
  acl: public_read
  on:
    repo: cucuso/scheduly-website
